/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1765 2010-02-11 09:51:13Z max.at.xam.de $) JavaScript extension on 5/29/11 6:28 PM
 */

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> Primarytopic </li>
 *   <li> Sha1sum_hex_ </li>
 *   <li> Topic </li>
 *   <li> Comment </li>
 *   <li> Label </li>
 *   <li> Member </li>
 *   <li> Type </li>
 * </ul>
 */
Document = function(rdf) {
    Thing.call(this, rdf);
   
    /** http://xmlns.com/foaf/0.1/Document */

    /** http://xmlns.com/foaf/0.1/primaryTopic */
    /** http://xmlns.com/foaf/0.1/sha1 */
    /** http://xmlns.com/foaf/0.1/topic */
    /** http://www.w3.org/2000/01/rdf-schema#comment */
    /** http://www.w3.org/2000/01/rdf-schema#label */
    /** http://www.w3.org/2000/01/rdf-schema#member */
    /** http://www.w3.org/1999/02/22-rdf-syntax-ns#type */

    var queryObject = function(rdf, from, predicate, to) {
        return rdf.where(from + ' ' + predicate + ' ' + to);
    }
 
    var Primarytopic = new Array();
    queryObject(rdf, "?Document", "foaf:Primarytopic", "?Primarytopic")
        .each(function() {
            Primarytopic.push(new org.ontoware.rdfreactor.schema.owl.Thing(rdf
                .where("Primarytopic a foaf:Primarytopic")
                .filter("authority", this.Primarytopic.value.authority))); 
        });
    this.Primarytopic = Primarytopic;
    
    var Sha1sum_hex_ = new Array();
    queryObject(rdf, "?Document", "foaf:Sha1sum_hex_", "?Sha1sum_hex_")
        .each(function() {
            Sha1sum_hex_.push(new Thing(rdf
                .where("Sha1sum_hex_ a foaf:Sha1sum_hex_")
                .filter("authority", this.Sha1sum_hex_.value.authority))); 
        });
    this.Sha1sum_hex_ = Sha1sum_hex_;
    
    var Topic = new Array();
    queryObject(rdf, "?Document", "foaf:Topic", "?Topic")
        .each(function() {
            Topic.push(new org.ontoware.rdfreactor.schema.owl.Thing(rdf
                .where("Topic a foaf:Topic")
                .filter("authority", this.Topic.value.authority))); 
        });
    this.Topic = Topic;
    
    var comment = new Array();
    queryObject(rdf, "?Document", "foaf:comment", "?comment")
        .each(function() {
            comment.push(new org.ontoware.rdfreactor.schema.owl.Thing(rdf
                .where("comment a foaf:comment")
                .filter("authority", this.comment.value.authority))); 
        });
    this.comment = comment;
    
    var label = new Array();
    queryObject(rdf, "?Document", "foaf:label", "?label")
        .each(function() {
            label.push(new org.ontoware.rdfreactor.schema.owl.Thing(rdf
                .where("label a foaf:label")
                .filter("authority", this.label.value.authority))); 
        });
    this.label = label;
    
    var member = new Array();
    queryObject(rdf, "?Document", "foaf:member", "?member")
        .each(function() {
            member.push(new org.ontoware.rdfreactor.schema.owl.Thing(rdf
                .where("member a foaf:member")
                .filter("authority", this.member.value.authority))); 
        });
    this.member = member;
    
    var type = new Array();
    queryObject(rdf, "?Document", "foaf:type", "?type")
        .each(function() {
            type.push(new org.ontoware.rdfreactor.schema.owl.Thing(rdf
                .where("type a foaf:type")
                .filter("authority", this.type.value.authority))); 
        });
    this.type = type;
    

    this.equals = function(o) {
        if(!(o instanceof Document)) {
            return false;
        }
        if(Thing.prototype.equals.call(this)) {
            return false;
        }
        if(this.comment.length == o.comment.length)
            for(var i = 0; i < this.comment.length; i++) {
                if(!this.comment.equals(o.comment)) {
                    return false;
                }
            }
        }
        if(this.label.length == o.label.length)
            for(var i = 0; i < this.label.length; i++) {
                if(!this.label.equals(o.label)) {
                    return false;
                }
            }
        }
        if(this.member.length == o.member.length)
            for(var i = 0; i < this.member.length; i++) {
                if(!this.member.equals(o.member)) {
                    return false;
                }
            }
        }
        if(this.type.length == o.type.length)
            for(var i = 0; i < this.type.length; i++) {
                if(!this.type.equals(o.type)) {
                    return false;
                }
            }
        }
        return true;
    }
    
}
Document.prototype = new Thing();
