/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1765 2010-02-11 09:51:13Z max.at.xam.de $) JavaScript extension on 5/29/11 6:28 PM
 */

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> Depicts </li>
 *   <li> Thumbnail </li>
 * </ul>
 */
Image = function(rdf) {
    Document.call(this, rdf);
   
    /** http://xmlns.com/foaf/0.1/Image */

    /** http://xmlns.com/foaf/0.1/depicts */
    /** http://xmlns.com/foaf/0.1/thumbnail */

    var queryObject = function(rdf, from, predicate, to) {
        return rdf.where(from + ' ' + predicate + ' ' + to);
    }
 
    var Depicts = new Array();
    queryObject(rdf, "?Image", "foaf:Depicts", "?Depicts")
        .each(function() {
            Depicts.push(new org.ontoware.rdfreactor.schema.owl.Thing(rdf
                .where("Depicts a foaf:Depicts")
                .filter("authority", this.Depicts.value.authority))); 
        });
    this.Depicts = Depicts;
    
    var Thumbnail = new Array();
    queryObject(rdf, "?Image", "foaf:Thumbnail", "?Thumbnail")
        .each(function() {
            Thumbnail.push(new Image(rdf
                .where("Thumbnail a foaf:Thumbnail")
                .filter("authority", this.Thumbnail.value.authority))); 
        });
    this.Thumbnail = Thumbnail;
    

    this.equals = function(o) {
        if(!(o instanceof Image)) {
            return false;
        }
        if(Document.prototype.equals.call(this)) {
            return false;
        }
        return true;
    }
    
}
Image.prototype = new Document();
