/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1765 2010-02-11 09:51:13Z max.at.xam.de $) JavaScript extension on 5/29/11 6:28 PM
 */

/**
 */
OnlineGamingAccount = function(rdf) {
    OnlineAccount.call(this, rdf);
   
    /** http://xmlns.com/foaf/0.1/OnlineGamingAccount */


    var queryObject = function(rdf, from, predicate, to) {
        return rdf.where(from + ' ' + predicate + ' ' + to);
    }
 

    this.equals = function(o) {
        if(!(o instanceof OnlineGamingAccount)) {
            return false;
        }
        if(OnlineAccount.prototype.equals.call(this)) {
            return false;
        }
        return true;
    }
    
}
OnlineGamingAccount.prototype = new OnlineAccount();
