/**
 * generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1765 2010-02-11 09:51:13Z max.at.xam.de $) JavaScript extension on 5/29/11 6:28 PM
 */

/**
 */
PersonalProfileDocument = function(rdf) {
    Document.call(this, rdf);
   
    /** http://xmlns.com/foaf/0.1/PersonalProfileDocument */


    var queryObject = function(rdf, from, predicate, to) {
        return rdf.where(from + ' ' + predicate + ' ' + to);
    }
 

    this.equals = function(o) {
        if(!(o instanceof PersonalProfileDocument)) {
            return false;
        }
        if(Document.prototype.equals.call(this)) {
            return false;
        }
        return true;
    }
    
}
PersonalProfileDocument.prototype = new Document();
